### ISSUE TITLE
Resize the images and video in the main README.md

### ISSUE THREAD

**Issue by web4locals** [web4locals/first_git#1]
I need to resize the mp4 video to mini size. 
(line 18)

Also, it would be nice to match the image sizes. (line 10-13)

**Comment by oerzn** [comment]
To resize the image in read.md :-


1.Upload picture by drag-and-drop in the text field
2. Replace `![image](https://your-image-url.type)` with 

`<img src="https://your-image-url.type" width="200" height="100">`

Adjust the height and width according to your need.

for ex:
`<img src="https://raw.githubusercontent.com/web4locals/first_git/main/assets/images/DARKSIDE.png" width="200" height="200">`
<img src="https://raw.githubusercontent.com/web4locals/first_git/main/assets/images/DARKSIDE.png" width="200" height="200">

**Comment by oerzn** [comment]
To resize the video:-
1. Use video tag, 
2. `<video width="500px" height="500px" 
        controls="controls"/> 
          
        <source src="vid.mp4" 
            type="video/mp4"> `
 for example:
`<video width="500px" height="500px" 
        controls="controls"/> 
          
        <source src="[vid.mp4](https://user-images.githubusercontent.com/103498656/170197513-cf069016-fa93-4f66-b430-721c212d909e.mp4
/video>)" 
            type="video/mp4"> `
<video width="500px" height="500px" 
        controls="controls"/> 
          
        <source src="[vid.mp4](https://user-images.githubusercontent.com/103498656/170197513-cf069016-fa93-4f66-b430-721c212d909e.mp4
/video>)" 
            type="video/mp4">
